### ISSUE TITLE
install.txt doesn't mention the need to install or configure fldigi

### ISSUE THREAD

**Issue by n1ai** [afarhan/sbitx#58]
See https://groups.io/g/BITX20/message/106035 and follow-up posts for more details.

Bottom line is if fldigi is not installed the text UI stops responding when you change bands.

This requirement isn't mentioned in install.txt 

I suggest that install.txt should include the fixes which are to install and configure fldigi to work with sbitx.

To fix, just do 'sudo apt install fldigi' and in the resulting configuration dialog or configuration menus, set the following key parameters:

```
  - Operator/Station:  
    Set station and operator callsigns and station locator/location
  - Soundcard(Audio)/Devices
    [X] PortAudio
        Capture:  Loopback: PCM (hw1:1)
        Playback: Loopback: PCM (hw2,0)
  - Rig(Rig Control)/Hamlib
      Rig: Hamlib Net Rigctl (Stable)
      Device: 127.0.0.1:4352
      [X] PTT via Hamlib command
```
